### ISSUE TITLE
User Login Problem

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/finalProject#3]
I am working to set up user login for bcrypt with mongoose based off of this article:
http://devsmash.com/blog/password-authentication-with-mongoose-and-bcrypt

I have this route in my server:
https://github.com/anastasiaalt/finalProject/blob/master/app.js

```
app.post('/login', function(req, res){
  var username = 'X';
  var password = 'Y';

  User.find({}, function(err){
    if (err) throw err;

    User.findOne({ username: username }, function(err, user) {
      if (err) throw err;

      user.comparePassword(password, function(err, isMatch) {
          if (err) throw err;
          console.log(password, isMatch);
      });
    });
  });

  res.redirect('/');

  console.log('no error');
});
```

That corresponds to my User model, which is here and contains this
https://github.com/anastasiaalt/finalProject/blob/master/models/user.js

```
 var user = this;
```

When I attempt to Log In with a username and password combination that is stored in my database, I am getting this error in my server console:

POST /login 302 20.947 ms - 46
/Users/anastasiaalt/finalProject/app.js:138
      user.comparePassword(password, function(err, isMatch) {
          ^

TypeError: Cannot read property 'comparePassword' of null

Which doesn't follow the outline of the example website I included above and it doesn't make sense given I define var user = this; in my User model.

My browser console is printing this when I click the submit button on my Log In form:
GET http://localhost:3000/ net::ERR_CONNECTION_REFUSED

The code for the Submit is here:
https://github.com/anastasiaalt/finalProject/blob/master/views/register.ejs

```
            <input class= "ui blue submit button" type="submit" value="Register">
```

**Comment by phlco** [comment]
if that user is null you should rry and console.log all the results and errors you get back

are you sure that user is in your db? that may be one reason it's null

**Comment by anastasiaalt** [comment]
The user I added to the database was jmar777 and the password was 'Password123'. In the terminal, I can see the user like this:

```
> db.users.find().pretty()
{
    "_id" : ObjectId("56a38fd1661579fbcccacb4b"),
    "first_name" : "Lily",
    "last_name" : "Alt",
    "gender" : "Female"
}
{
    "_id" : ObjectId("56a4e7bec91f72c77b9895dc"),
    "username" : "jmar777",
    "password" : "$2a$10$xQ8b1BNDb8vlgtDngjFlAOKEWgX37ugvBXHLg/nBOQJEGbSrjXzOG",
    "__v" : 0
}
```

I hashed the password with bcrypt, which is why it looks this way now as I understand it.

I just did a test in which I added the user Phil with password 'cupcakes' to the database directly from the terminal and I did not hash or encrypt the password at all. When I attempt to log in, I get the same error as with my user and hashed password. 

What else do you recommend I console log exactly to see what's causing it? I am feeling quite stumped

**Comment by phlco** [comment]
whats with the x and y in your code?

**Comment by anastasiaalt** [comment]
I was getting an error that username and password were not defined so I was playing around with different combinations. If I take this out, I get

```
/Users/anastasiaalt/finalProject/app.js:135
    User.findOne({ username: username }, function(err, user) {
                             ^

ReferenceError: username is not defined
```

I have been studying the code more and playing around and I think I am not properly linking the username and password I type through the login back to this test. I am studying Anna's Friday morning example by contrast and I am struggling to see something she includes that I forget....

**Comment by phlco** [comment]
yes it looks like you're missing pulling them out of req.body

**Comment by anastasiaalt** [comment]
I changed those lines of code to

```
  var user = new User(req.body.user);
```

but am getting thrown the same error...

https://github.com/anastasiaalt/finalProject/blob/master/app.js

**Comment by phlco** [comment]
After a user has signed up they return to the index where they can login with username and password.
When you click submit the following error is logged to the console

``` js
// finalProject/app.js:134
    User.findOne({ username: username }, function(err, user) {
                             ^

ReferenceError: username is not defined
```

You should start thinking why `username` might not be defined...

Here's the entire piece of code from your `app.js`

``` js
app.post('/login', function(req, res){
  var user = new User(req.body.user);

  User.find({}, function(err){
    if (err) throw err;

    User.findOne({ username: username }, function(err, user) {
      if (err) throw err;

      user.comparePassword(password, function(err, isMatch) {
          if (err) throw err;
          console.log(password, isMatch);
      });
    });
  });

  res.redirect('/');

  console.log('no error');
});
```

If you were to fix that you'd get the following error

``` js
// app.js:140
      user.comparePassword(password, function(err, isMatch) {
          ^

TypeError: Cannot read property 'comparePassword' of null
```

Here's the full block of code:

``` js
    User.findOne({ username: username }, function(err, user) {
      if (err) throw err;

      user.comparePassword(password, function(err, isMatch) {
          if (err) throw err;
          console.log(password, isMatch);
      });
    });
```

You should console.log all the returned values. You'll see that `err` and `null` are both null. Then you should think why aren't my users being saved? Where does that happen?

If you look at your route handler for `/register` you should console.log the body of the request:

You'll get something like this

```
{ first_name: 'dave',
  last_name: 'dave',
  username: 'dave',
  password: 'dave' }
```

In your code to save a user you have the following:

``` js
  var user = new User(req.body.user);
```

But I don't see a key in your `req.body` for "user".  You can only use that syntax if you set up your form like this:

```
<input type="text" name="user[username]">
```

**Comment by anastasiaalt** [comment]
Hi,

First, thank you so much for detailing out the flow of this all step by step and pointing out what I should be thinking or questioning to better troubleshoot my own errors. I really appreciate it and despite the troubles, I do feel I am learning and getting there incredibly slowly.... sort of like a drunk tortoise climbing a hill.... about that fast.

Unfortunately, something is still very much confusing me. I have read your note many times and tinkered with various changes in the code. I am both having no luck getting it to work and not following the logic/understanding the flow of information towards the end of what you write especially.

When I add a new user, I can see the post in the server console as:

```
{ user: 
   { first_name: 'Antonia',
     last_name: 'Toppol',
     username: 'anttop' },
  password: '1234' }
```

I can see when I go into the collection from the command line that neither the user nor any of the information about the user (first name last name, password) is being saved in the database.

You say to expect something like the set of four key value pairs below, which makes sense to me given the way I have the form and the way I designed the schema:

```
{ first_name: 'dave',
  last_name: 'dave',
  username: 'dave',
  password: 'dave' }
```

You write: "But I don't see a key in your req.body for "user". You can only use that syntax if you set up your form like this:" 

However, what I see in the server console appears to include a user key with nested information inside of it and this looks different than what you say to anticipate and even what I would have expected to see given the way I designed the schema.

```
app.post('/posts', function(req, res){
 // TODO set the post's posted by to whoever is logged in's name
  var post = new Post(req.body.post);
  post.save(function(err, result){
    console.log(req.body);
    res.redirect('/');
  });
});
```

I tried changing my registration form to the way you indicated with no luck
https://github.com/anastasiaalt/finalProject/blob/master/views/register.ejs

and I updated the login form in the same manner

```
            <div class="one field">
                <form method="POST" action="/login">
                    <label for="username">Username</label>
                    <input type="text" name="user[username]" placeholder="Username" requiredautofocus>
            </div>
            <div class="one field">
                    <label for="password" class="sr-only">Password</label>
                    <input type="password" name="user[password]" id="password" class="form-control" placeholder="Password">
            </div>
            <div>
                    <button class="ui blue submit button" type="submit">Login</button>
                </form>
            </div>
```

**Comment by phlco** [comment]
You need to make sure you're console.logging all your errors.  For instance when creating a user

``` js
user.save(function(err, result) {
    console.log(req.body);
    res.redirect('/');
  });
```

You should console.log that error.  You'd see

``` js
{ [ValidationError: User validation failed]
  message: 'User validation failed',
  name: 'ValidationError',
  errors: 
   { password: 
      { [ValidatorError: Path `password` is required.]
        properties: [Object],
        message: 'Path `password` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'password',
        value: undefined } } } undefined
```

That would lead you to think "but I AM passing a password, right??" And then check the signup form.

``` html
            <form class="" method="post" action="/register">
<!-- the error must be happening somewhere around here -->
                <input type="password" name="password" id="user[password]" class="" placeholder="Password" required>

            </form>
```

Remember `name="password"` means it's not put into the same object as `req.body.user`  If you want to add it in you need to change it to `name="user[password]"`
